### ISSUE TITLE
Preparing files for Apollo

### ISSUE THREAD

**Issue by mictadlo** [GMOD/docker-apollo#36]
Hi, 
How is it possible to prepare files for Apollo when using Apollo inside a docker container?

Thank you in advance,

Michal

**Comment by nathandunn** [comment]
I think so . . . depends on the file you are talking about:

docker run -it -v /jbrowse/root/directory/:/data -v postgres-data:/var/lib/postgresql -p 8888:8080 gmod/apollo:latest

Anything in /jbrowse/root/directory will be visible as ‘/data’ to the server.    Note, to keep the database persistent you have to use the postgres-data link below.

Otherwise you can set most of the properties from the command-line as below that correlate with what is in the apollo-config.groovy.
  
docker run -e "env_var_name=another_value" alpine env
Was that what you were looking to change?

I tried to clarify it a little bit here: https://github.com/GMOD/docker-apollo/blob/master/README.md <https://github.com/GMOD/docker-apollo/blob/master/README.md>

Nathan
